name: Format

on: push

jobs:
  postprocessing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - uses: JohnnyMorganz/stylua-action@1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: format with stylua"
