name: Format

on: push

jobs:
  postprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Format code with stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: format with stylua"
